str : btree list stack_list item_int main 
	gcc btree.o list.o stack_list.o item_int.o main.o -o array.exe

btree :
	gcc  -c btree.c 

list :
	gcc -c list.c

stack_list :
	gcc -c stack_list.c

item_int :
	gcc -c item_int.c

main : 
	gcc -c main.c

clean : 
	rm -f *.o *.exe
