str : btree list stack_list item_str main 
	gcc btree.o list.o stack_list.o item_str.o main.o -o array.exe

btree :
	gcc  -c btree.c 

list :
	gcc -c list.c

stack_list :
	gcc -c stack_list.c

item_str :
	gcc -c item_str.c

main : 
	gcc -c main.c

clean : 
	rm -f *.o *.exe
